aliriodi/3DSeller

- package-lock.json
- package.json
- src/components/CardDetail/CardDetail.jsx
- src/components/Products/Products.jsx
- src/pages/_app.tsx
- src/pages/api/products/[id].js
- src/redux/DSellerActions.js
- src/redux/DSellerSlice.ts
probar renderiza detalle nombre
> Probar el Vcard-Detail

- src/components/CardDetail/CardDetail.jsx
- src/components/Products/Products.jsx
> Tarjeta Detalles V1 sin estilos

- src/components/CardDetail/CardDetail.jsx
- src/components/CreateP/CreateP.jsx
- src/components/Nav/Nav.jsx
- src/redux/DSellerActions.js
- src/redux/DSellerSlice.ts
> Nombrequequieras

- src/components/CreateP/CreateP.jsx
- src/components/Nav/Nav.jsx
agregue la etiqueta Link que es nativa de next, para que el codigo sea un poco mas prolijo y todos los elementos del nav den respuesta elimine algo de codigo en cada elemento <a> pero cada enlace sigue funcionando de forma correcta
> Refactornav

- src/components/CreateP/CreateP.jsx
- src/components/Products/Products.jsx
El plan original de la rama era trabajar algunos estilos pero al final hice cambios solo a la search para que funcione con un boton, como ordeno el amo y Sr =)
> search bar cambiada

- src/components/Products/Products.jsx
- src/redux/DSellerSlice.ts
Repito el mensaje =D el search ya vuelve a tener funcionalidad, elimine la gran mayoria de las referencias al codigo que ocupaba estados locales, no estoy seguro de si todas por que estoy medio dormido, pero hay que revisar por que las validaciones no permiten que uno solo item este en el estado de los filtros, ya que si por lo que sea el Search encuentra mas de un elemento en el arreglo los demas filtros no se podran aplicar a el, esta mejora fue solo para salir del paso, pero tan pronto como se arregle lo de las validaciones el codigo no requiere mas que cambiar mi dsipatch por el correcto ♥
> El search vuelve a funcionar

- src/models/User.js
- src/pages/api/auth/[...auth0].js
- src/pages/api/user/[id].js
- src/pages/api/user/index.js
model de usuarios 
ruta /api//user
/api/user/id for detail solo 1
> models uauraio 1

- src/components/LogButton/LogButton.jsx
/src/component/Logbuton 
<Link href={"https://3dseller.vercel.app/"} legacyBehavior>
<div className="container-logout" ><div className="logout-item"> x</div>
</div>
</Link>:null}
EN LOCAL DEBE ESTAR LA REF http://localhost:3000/api/auth/logout
> login con logout boton de x cuando esta renderizado es el logout x

- src/components/FavButton/FavButton.jsx
- src/components/LogButton/LogButton.jsx
- src/redux/DSellerActions.js
los Favoritos ya van para el back en el formato solicitado { favorites: [id1,id2,id3], user: "todos los datos del usuario }
> Formato favs back

- src/components/FavButton/FavButton.jsx
- src/redux/DSellerActions.js
BD local ya guarda elementos en Favotritos del FE 
ahora viene creacion de usuarios cada vez que se autentique
> trabajando en la BD local ya guarda FAVORITOS como array de objetos

- src/components/CardDetail/CardDetail.jsx
- src/components/CreateP/CreateP.jsx
- src/components/FavButton/FavButton.jsx
- src/components/FavButton/Favoritos.jsx
- src/components/FavButton/NoFavsYet.jsx
- src/components/Nav/Nav.jsx
- src/components/Products/Products.jsx
- src/components/Vcard/Vcard.jsx
- src/pages/favoritos.tsx
Lista la pagina que renderiza solo los favoritos =) ♥
> Componente favoritos

- src/components/FavButton/Favoritos.jsx
- src/components/FavButton/NoFavsYet.jsx
- src/components/Nav/Nav.jsx
- src/components/Products/Products.jsx
- src/components/Vcard/Vcard.jsx
La informacion del almacenamiento local ya no se carga para usuarios no registrados, se agrego una ruta en el componente para sugerirle al usuario registrase en la pagina
> bugs corregidos en componente favoritos

- src/components/Footer/Footer.jsx
- src/pages/_app.tsx
faltan unos pocos estilos y unas imagenes para las redes sociales nomas :V
> Footer Integrado

- src/components/LogButton/LogButton.jsx
> se actualiza log button

- src/components/CardDetail/CardDetail.jsx
- src/pages/api/payment/mail-customer.js
- src/pages/api/payment/paypal.js
Hay error en las promesas, correo se manda al clickear en el boton paypal
> feat: mandar correos de compra al usuario loggeado

- src/components/CardDetail/CardDetail.jsx
> feat: singin button cuando el usuaro no esta loggeado

- package-lock.json
- package.json
- src/components/CreateP/CreateP.jsx
Clodinary andando crear pull request
> Cloudynary

- src/components/CardDetail/CardDetail.jsx
- src/pages/api/payment/mail-customer.js
- src/pages/purchases/[orderid].jsx
> add: email for a successfully completed purchase implemented

- src/components/CardDetail/CardDetail.jsx
- src/models/Purchase.js
- src/pages/api/payment/mail-customer.js
- src/pages/api/purchase/[id].js
- src/pages/api/purchase/index.js
Falta corroborar que funcione en Deploy
> add: guardan compra en base datos

- src/components/Products/Products.jsx
El codigo entero del paginado ahora es sostenible, y por si solo funcionara correctamente incluso agregando nuevos productos
> Paginado Sostenible

- src/components/CardDetail/CardDetail.jsx
- src/models/Purchase.js
- src/pages/api/[...purchase].js
> fix: relacion de id usuario con su compra

- src/models/Purchase.js
- src/pages/api/[...purchase].js
- src/pages/purchases/[orderid].jsx
falta relacionar compra con el Producto, teengo que volver añadir los estilos al global.css, esperando PR aprobado de nahuel
> add: datos de compra

- src/components/CardDetail/CardDetail.jsx
- src/pages/api/[...purchase].js
- src/pages/api/payment/mail-customer.js
- src/pages/purchases/[orderid].jsx
- src/styles/globals.css
falta testear que funcione todo bien en deploy
> add: estilos, funcion en frontend agregada

- src/components/PanelAdmin/PanelAdmin.jsx
- src/pages/api/count/[...count].js
> add: mostrando numero de compras en panel admin

- src/pages/api/verify/index.js
> add: endpoint para traer compras con relacion id usuario e id producto
